# Generated by Django 4.1 on 2023-08-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=100)),
                ('prom', models.IntegerField()),
            ],
        ),
    ]
